enabled: true
backend:
  image: registry.relizahub.com/119a99d7-3992-4de4-91dc-395c70272e93-public/rebom-backend
  replicaCount: 1
  regcred: none
frontend:
  image: registry.relizahub.com/119a99d7-3992-4de4-91dc-395c70272e93-public/rebom-frontend
  replicaCount: 1
  regcred: none
postgresql:
  image: postgres:14.1
  defaultSecret: true
  replicaCount: 1
  storage: 5Gi
flyway:
  image: flyway/flyway:8.4.4-alpine
ingress:
  minimalIngressEnabled: true
  traefikEnabled: false
  host: localhost

ecr-regcred:
  enabled: false