apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rebom-postgres
  namespace: rebom
spec:
  template:
    spec:
      containers:
        - name: postgres-container
          image: docker.io/library/postgres@sha256:c62fdb7fd6f519ef425c54760894c74e8d0cb04fbf4f7d3d79aafd86bae24edd
