on: [push]

name: Build Docker Image And Submit Metadata To Reliza Hub

permissions:
  contents: write

jobs:
  build-backend:
    name: Build And Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit Release metadata action
        uses: relizaio/reliza-docker-action@2.1
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/119a99d7-3992-4de4-91dc-395c70272e93-public
          image_name: rebom-backend
          reliza_api_id: ${{ secrets.RELIZA_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
          path: backend
          reliza_project_id: dafcfed2-f327-439b-b128-544b5d75aa39
          enable_sbom: 'true'
  build-frontend:
    name: Build And Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit Release metadata action
        uses: relizaio/reliza-docker-action@2.1
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/119a99d7-3992-4de4-91dc-395c70272e93-public
          image_name: rebom-frontend
          reliza_api_id: ${{ secrets.RELIZA_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
          path: frontend
          reliza_project_id: 9768dd74-0e7f-418d-8ee7-0e73c653f7bb
          enable_sbom: 'true'
  build-helm:
    name: Build And Push Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit Release metadata action
        uses: relizaio/reliza-helm-action@2.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com/119a99d7-3992-4de4-91dc-395c70272e93-public
          helm_chart_name: rebom
          reliza_api_id: ${{ secrets.RELIZA_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_API_KEY }}
          path: helm
          reliza_project_id: 3c765ff1-c4ef-4838-91c4-5497bfd0ab2b
